// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ImportJobStatus Response - POCO object
    /// </summary>
    public partial class ImportJobStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorImportJobStatusResponse
        /// class.
        /// </summary>
        public ImportJobStatusResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorImportJobStatusResponse
        /// class.
        /// </summary>
        /// <param name="jobName">Gets or sets the name for the job
        /// overall</param>
        /// <param name="fileProcessingStatus">Gets or sets the file processing
        /// status.</param>
        /// <param name="pageIndex">Gets or sets the page index.</param>
        /// <param name="totalPageCount">Gets or sets the total number of
        /// pages.</param>
        public ImportJobStatusResponse(string jobName, IList<ImportJobFileStatusInfo> fileProcessingStatus, int pageIndex, int totalPageCount)
        {
            JobName = jobName;
            FileProcessingStatus = fileProcessingStatus;
            PageIndex = pageIndex;
            TotalPageCount = totalPageCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the name for the job overall
        /// </summary>
        [JsonProperty(PropertyName = "jobName")]
        public string JobName { get; set; }

        /// <summary>
        /// Gets or sets the file processing status.
        /// </summary>
        [JsonProperty(PropertyName = "fileProcessingStatus")]
        public IList<ImportJobFileStatusInfo> FileProcessingStatus { get; set; }

        /// <summary>
        /// Gets or sets the page index.
        /// </summary>
        [JsonProperty(PropertyName = "pageIndex")]
        public int PageIndex { get; set; }

        /// <summary>
        /// Gets or sets the total number of pages.
        /// </summary>
        [JsonProperty(PropertyName = "totalPageCount")]
        public int TotalPageCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (JobName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "JobName");
            }
            if (FileProcessingStatus == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FileProcessingStatus");
            }
            if (FileProcessingStatus != null)
            {
                foreach (var element in FileProcessingStatus)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
