// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MicrosoftAspNetCoreMvcVirtualFileResult
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftAspNetCoreMvcVirtualFileResult class.
        /// </summary>
        public MicrosoftAspNetCoreMvcVirtualFileResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftAspNetCoreMvcVirtualFileResult class.
        /// </summary>
        public MicrosoftAspNetCoreMvcVirtualFileResult(string fileName = default(string), object fileProvider = default(object), string contentType = default(string), string fileDownloadName = default(string), System.DateTime? lastModified = default(System.DateTime?), MicrosoftNetHttpHeadersEntityTagHeaderValue entityTag = default(MicrosoftNetHttpHeadersEntityTagHeaderValue))
        {
            FileName = fileName;
            FileProvider = fileProvider;
            ContentType = contentType;
            FileDownloadName = fileDownloadName;
            LastModified = lastModified;
            EntityTag = entityTag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileProvider")]
        public object FileProvider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public string ContentType { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileDownloadName")]
        public string FileDownloadName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastModified")]
        public System.DateTime? LastModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entityTag")]
        public MicrosoftNetHttpHeadersEntityTagHeaderValue EntityTag { get; set; }

    }
}
