// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MicrosoftExtensionsPrimitivesStringSegment
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftExtensionsPrimitivesStringSegment class.
        /// </summary>
        public MicrosoftExtensionsPrimitivesStringSegment()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftExtensionsPrimitivesStringSegment class.
        /// </summary>
        public MicrosoftExtensionsPrimitivesStringSegment(string buffer = default(string), int? offset = default(int?), int? length = default(int?), string value = default(string), bool? hasValue = default(bool?))
        {
            Buffer = buffer;
            Offset = offset;
            Length = length;
            Value = value;
            HasValue = hasValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "buffer")]
        public string Buffer { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offset")]
        public int? Offset { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "length")]
        public int? Length { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasValue")]
        public bool? HasValue { get; private set; }

    }
}
