// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MicrosoftNetHttpHeadersEntityTagHeaderValue
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftNetHttpHeadersEntityTagHeaderValue class.
        /// </summary>
        public MicrosoftNetHttpHeadersEntityTagHeaderValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftNetHttpHeadersEntityTagHeaderValue class.
        /// </summary>
        public MicrosoftNetHttpHeadersEntityTagHeaderValue(MicrosoftExtensionsPrimitivesStringSegment tag = default(MicrosoftExtensionsPrimitivesStringSegment), bool? isWeak = default(bool?))
        {
            Tag = tag;
            IsWeak = isWeak;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public MicrosoftExtensionsPrimitivesStringSegment Tag { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isWeak")]
        public bool? IsWeak { get; private set; }

    }
}
