// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A class containing information related to the document after it has
    /// been processed in a specific model training
    /// </summary>
    public partial class ProcessedDocumentInfo
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsTextTranslatorProcessedDocumentInfo class.
        /// </summary>
        public ProcessedDocumentInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsTextTranslatorProcessedDocumentInfo class.
        /// </summary>
        /// <param name="id">Gets or Sets Id</param>
        /// <param name="modelId">Gets or Sets parent model Id</param>
        /// <param name="documentId">Gets or Sets document set from which the
        /// documents were derived</param>
        /// <param name="alignedSentenceCount">Aligned sentence count after
        /// sentence alignment is executed</param>
        /// <param name="usedSentenceCount">Sentences used after filtering and
        /// auto selection occur</param>
        public ProcessedDocumentInfo(long id, long modelId, long documentId, long? alignedSentenceCount = default(long?), long? usedSentenceCount = default(long?))
        {
            Id = id;
            ModelId = modelId;
            DocumentId = documentId;
            AlignedSentenceCount = alignedSentenceCount;
            UsedSentenceCount = usedSentenceCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets parent model Id
        /// </summary>
        [JsonProperty(PropertyName = "modelId")]
        public long ModelId { get; set; }

        /// <summary>
        /// Gets or Sets document set from which the documents were derived
        /// </summary>
        [JsonProperty(PropertyName = "documentId")]
        public long DocumentId { get; set; }

        /// <summary>
        /// Gets or sets aligned sentence count after sentence alignment is
        /// executed
        /// </summary>
        [JsonProperty(PropertyName = "alignedSentenceCount")]
        public long? AlignedSentenceCount { get; set; }

        /// <summary>
        /// Gets or sets sentences used after filtering and auto selection
        /// occur
        /// </summary>
        [JsonProperty(PropertyName = "usedSentenceCount")]
        public long? UsedSentenceCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
