// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TextTranslatorDALDocumentType
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALDocumentType
        /// class.
        /// </summary>
        public TextTranslatorDALDocumentType()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALDocumentType
        /// class.
        /// </summary>
        public TextTranslatorDALDocumentType(int? id = default(int?), string docType = default(string), IList<TextTranslatorDALDocument> documents = default(IList<TextTranslatorDALDocument>), IList<TextTranslatorDALUploadHistory> uploadHistoryRecords = default(IList<TextTranslatorDALUploadHistory>))
        {
            Id = id;
            DocType = docType;
            Documents = documents;
            UploadHistoryRecords = uploadHistoryRecords;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "docType")]
        public string DocType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documents")]
        public IList<TextTranslatorDALDocument> Documents { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uploadHistoryRecords")]
        public IList<TextTranslatorDALUploadHistory> UploadHistoryRecords { get; set; }

    }
}
