// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The input class for model requests.
    /// </summary>
    public partial class TextTranslatorModelsRequestTextTranslatorModelRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsRequestTextTranslatorModelRequest class.
        /// </summary>
        public TextTranslatorModelsRequestTextTranslatorModelRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsRequestTextTranslatorModelRequest class.
        /// </summary>
        /// <param name="name">Gets or sets Name</param>
        /// <param name="projectId">Gets or sets the Id of the project to which
        /// the model belongs.</param>
        /// <param name="documentIds">List of DocumentIds</param>
        /// <param name="isTuningAuto">Gets or sets IsTuningAuto</param>
        /// <param name="isTestingAuto">Gets or sets IsTestingAuto</param>
        /// <param name="isAutoDeploy">Gets or sets IsAutoDeploy</param>
        /// <param name="isAutoTrain">Gets or sets IsAutoTrain. If AutoTrain is
        /// not set,
        /// defaults to true. If AutoTrain is set to false,
        /// it will create the model in a draft state.</param>
        /// <param name="autoDeployThreshold">Gets or sets the auto deployment
        /// bleu score diff threshold. Auto-deploy will occur when the
        /// bleu score threshold meets or exceeds the specified
        /// minimum.</param>
        public TextTranslatorModelsRequestTextTranslatorModelRequest(string name, System.Guid projectId, IList<long?> documentIds = default(IList<long?>), bool? isTuningAuto = default(bool?), bool? isTestingAuto = default(bool?), bool? isAutoDeploy = default(bool?), bool? isAutoTrain = default(bool?), double? autoDeployThreshold = default(double?))
        {
            Name = name;
            ProjectId = projectId;
            DocumentIds = documentIds;
            IsTuningAuto = isTuningAuto;
            IsTestingAuto = isTestingAuto;
            IsAutoDeploy = isAutoDeploy;
            IsAutoTrain = isAutoTrain;
            AutoDeployThreshold = autoDeployThreshold;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets Name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Id of the project to which the model belongs.
        /// </summary>
        [JsonProperty(PropertyName = "projectId")]
        public System.Guid ProjectId { get; set; }

        /// <summary>
        /// Gets or sets list of DocumentIds
        /// </summary>
        [JsonProperty(PropertyName = "documentIds")]
        public IList<long?> DocumentIds { get; set; }

        /// <summary>
        /// Gets or sets IsTuningAuto
        /// </summary>
        [JsonProperty(PropertyName = "isTuningAuto")]
        public bool? IsTuningAuto { get; set; }

        /// <summary>
        /// Gets or sets IsTestingAuto
        /// </summary>
        [JsonProperty(PropertyName = "isTestingAuto")]
        public bool? IsTestingAuto { get; set; }

        /// <summary>
        /// Gets or sets IsAutoDeploy
        /// </summary>
        [JsonProperty(PropertyName = "isAutoDeploy")]
        public bool? IsAutoDeploy { get; set; }

        /// <summary>
        /// Gets or sets IsAutoTrain. If AutoTrain is not set,
        /// defaults to true. If AutoTrain is set to false,
        /// it will create the model in a draft state.
        /// </summary>
        [JsonProperty(PropertyName = "isAutoTrain")]
        public bool? IsAutoTrain { get; set; }

        /// <summary>
        /// Gets or sets the auto deployment bleu score diff threshold.
        /// Auto-deploy will occur when the
        /// bleu score threshold meets or exceeds the specified minimum.
        /// </summary>
        [JsonProperty(PropertyName = "autoDeployThreshold ")]
        public double? AutoDeployThreshold { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
