// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A class for the file information.
    /// </summary>
    public partial class TextTranslatorModelsTextTranslatorFileInfo
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsTextTranslatorFileInfo class.
        /// </summary>
        public TextTranslatorModelsTextTranslatorFileInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsTextTranslatorFileInfo class.
        /// </summary>
        /// <param name="id">Gets or sets Id</param>
        /// <param name="fileName">Gets or sets the File Name</param>
        /// <param name="language">Gets or sets the language.</param>
        /// <param name="uploadDate">Gets or sets UploadDate</param>
        /// <param name="extractedSentenceCount">Gets or sets
        /// ExtractedSentenceCount</param>
        public TextTranslatorModelsTextTranslatorFileInfo(long? id = default(long?), string fileName = default(string), TextTranslatorModelsTextTranslatorLanguage language = default(TextTranslatorModelsTextTranslatorLanguage), System.DateTime? uploadDate = default(System.DateTime?), int? extractedSentenceCount = default(int?))
        {
            Id = id;
            FileName = fileName;
            Language = language;
            UploadDate = uploadDate;
            ExtractedSentenceCount = extractedSentenceCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets Id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or sets the File Name
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets the language.
        /// </summary>
        [JsonProperty(PropertyName = "language")]
        public TextTranslatorModelsTextTranslatorLanguage Language { get; set; }

        /// <summary>
        /// Gets or sets UploadDate
        /// </summary>
        [JsonProperty(PropertyName = "uploadDate")]
        public System.DateTime? UploadDate { get; set; }

        /// <summary>
        /// Gets or sets ExtractedSentenceCount
        /// </summary>
        [JsonProperty(PropertyName = "extractedSentenceCount")]
        public int? ExtractedSentenceCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Language != null)
            {
                Language.Validate();
            }
        }
    }
}
