// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALProjectBilling
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALProjectBilling
        /// class.
        /// </summary>
        public TextTranslatorDALProjectBilling()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALProjectBilling
        /// class.
        /// </summary>
        public TextTranslatorDALProjectBilling(long? id = default(long?), System.DateTime? lastBillingDate = default(System.DateTime?), TextTranslatorDALProject project = default(TextTranslatorDALProject), System.Guid? projectId = default(System.Guid?), TextTranslatorDALRegion region = default(TextTranslatorDALRegion), int? regionId = default(int?))
        {
            Id = id;
            LastBillingDate = lastBillingDate;
            Project = project;
            ProjectId = projectId;
            Region = region;
            RegionId = regionId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastBillingDate")]
        public System.DateTime? LastBillingDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public TextTranslatorDALProject Project { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectId")]
        public System.Guid? ProjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "region")]
        public TextTranslatorDALRegion Region { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "regionId")]
        public int? RegionId { get; set; }

    }
}
