// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALTest
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALTest class.
        /// </summary>
        public TextTranslatorDALTest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALTest class.
        /// </summary>
        public TextTranslatorDALTest(long? id = default(long?), string name = default(string), long? modelId = default(long?), byte[] status = default(byte[]), int? sentenceCount = default(int?), double? baselineBleuScorePunctuated = default(double?), double? bleuScorePunctuated = default(double?), double? baselineBleuScoreUnpunctuated = default(double?), double? bleuScoreUnpunctuated = default(double?), double? baselineBleuScoreCipunctuated = default(double?), double? bleuScoreCipunctuated = default(double?), double? baselineBleuScoreCiunpunctuated = default(double?), double? bleuScoreCiunpunctuated = default(double?), System.Guid? createdBy = default(System.Guid?), System.Guid? modifiedBy = default(System.Guid?), TextTranslatorDALApplicationUser createdByNavigation = default(TextTranslatorDALApplicationUser), TextTranslatorDALModel model = default(TextTranslatorDALModel), TextTranslatorDALApplicationUser modifiedByNavigation = default(TextTranslatorDALApplicationUser))
        {
            Id = id;
            Name = name;
            ModelId = modelId;
            Status = status;
            SentenceCount = sentenceCount;
            BaselineBleuScorePunctuated = baselineBleuScorePunctuated;
            BleuScorePunctuated = bleuScorePunctuated;
            BaselineBleuScoreUnpunctuated = baselineBleuScoreUnpunctuated;
            BleuScoreUnpunctuated = bleuScoreUnpunctuated;
            BaselineBleuScoreCipunctuated = baselineBleuScoreCipunctuated;
            BleuScoreCipunctuated = bleuScoreCipunctuated;
            BaselineBleuScoreCiunpunctuated = baselineBleuScoreCiunpunctuated;
            BleuScoreCiunpunctuated = bleuScoreCiunpunctuated;
            CreatedBy = createdBy;
            ModifiedBy = modifiedBy;
            CreatedByNavigation = createdByNavigation;
            Model = model;
            ModifiedByNavigation = modifiedByNavigation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modelId")]
        public long? ModelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public byte[] Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentenceCount")]
        public int? SentenceCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baselineBleuScorePunctuated")]
        public double? BaselineBleuScorePunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bleuScorePunctuated")]
        public double? BleuScorePunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baselineBleuScoreUnpunctuated")]
        public double? BaselineBleuScoreUnpunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bleuScoreUnpunctuated")]
        public double? BleuScoreUnpunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baselineBleuScoreCipunctuated")]
        public double? BaselineBleuScoreCipunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bleuScoreCipunctuated")]
        public double? BleuScoreCipunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "baselineBleuScoreCiunpunctuated")]
        public double? BaselineBleuScoreCiunpunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bleuScoreCiunpunctuated")]
        public double? BleuScoreCiunpunctuated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public System.Guid? CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public System.Guid? ModifiedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdByNavigation")]
        public TextTranslatorDALApplicationUser CreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public TextTranslatorDALModel Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedByNavigation")]
        public TextTranslatorDALApplicationUser ModifiedByNavigation { get; set; }

    }
}
