// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALProjectBillingAudit
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALProjectBillingAudit class.
        /// </summary>
        public TextTranslatorDALProjectBillingAudit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALProjectBillingAudit class.
        /// </summary>
        public TextTranslatorDALProjectBillingAudit(long? id = default(long?), System.DateTime? billingDate = default(System.DateTime?), string billingType = default(string), string description = default(string), TextTranslatorDALProject project = default(TextTranslatorDALProject), System.Guid? projectId = default(System.Guid?))
        {
            Id = id;
            BillingDate = billingDate;
            BillingType = billingType;
            Description = description;
            Project = project;
            ProjectId = projectId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billingDate")]
        public System.DateTime? BillingDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billingType")]
        public string BillingType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public TextTranslatorDALProject Project { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectId")]
        public System.Guid? ProjectId { get; set; }

    }
}
