// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The input class for model update requests.
    /// </summary>
    public partial class TextTranslatorModelsRequestTextTranslatorProjectUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsRequestTextTranslatorProjectUpdateRequest
        /// class.
        /// </summary>
        public TextTranslatorModelsRequestTextTranslatorProjectUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsRequestTextTranslatorProjectUpdateRequest
        /// class.
        /// </summary>
        /// <param name="name">Gets or sets Name</param>
        /// <param name="categoryDescriptor">Gets or sets
        /// CategoryDescriptor</param>
        /// <param name="description">Gets or sets Description</param>
        /// <param name="label">Gets or sets the project label.</param>
        public TextTranslatorModelsRequestTextTranslatorProjectUpdateRequest(string name = default(string), string categoryDescriptor = default(string), string description = default(string), string label = default(string))
        {
            Name = name;
            CategoryDescriptor = categoryDescriptor;
            Description = description;
            Label = label;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets Name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets CategoryDescriptor
        /// </summary>
        [JsonProperty(PropertyName = "categoryDescriptor")]
        public string CategoryDescriptor { get; set; }

        /// <summary>
        /// Gets or sets Description
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the project label.
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

    }
}
