// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ImportFiles response.
    /// Return the job ids for imported files
    /// </summary>
    public partial class TextTranslatorApiModelsResponseTestTranslatorImportFilesResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorApiModelsResponseTestTranslatorImportFilesResponse
        /// class.
        /// </summary>
        public TextTranslatorApiModelsResponseTestTranslatorImportFilesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorApiModelsResponseTestTranslatorImportFilesResponse
        /// class.
        /// </summary>
        /// <param name="jobId">Gets or sets the job identifier.</param>
        /// <param name="filesAcceptedForProcessing">Gets or sets the files
        /// accepted for processing.</param>
        public TextTranslatorApiModelsResponseTestTranslatorImportFilesResponse(System.Guid? jobId = default(System.Guid?), IList<string> filesAcceptedForProcessing = default(IList<string>))
        {
            JobId = jobId;
            FilesAcceptedForProcessing = filesAcceptedForProcessing;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the job identifier.
        /// </summary>
        [JsonProperty(PropertyName = "jobId")]
        public System.Guid? JobId { get; set; }

        /// <summary>
        /// Gets or sets the files accepted for processing.
        /// </summary>
        [JsonProperty(PropertyName = "filesAcceptedForProcessing")]
        public IList<string> FilesAcceptedForProcessing { get; set; }

    }
}
