// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALModelDocuments
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALModelDocuments
        /// class.
        /// </summary>
        public TextTranslatorDALModelDocuments()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALModelDocuments
        /// class.
        /// </summary>
        public TextTranslatorDALModelDocuments(long? id = default(long?), long? modelId = default(long?), long? documentId = default(long?), TextTranslatorDALDocument document = default(TextTranslatorDALDocument), TextTranslatorDALModel model = default(TextTranslatorDALModel))
        {
            Id = id;
            ModelId = modelId;
            DocumentId = documentId;
            Document = document;
            Model = model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modelId")]
        public long? ModelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentId")]
        public long? DocumentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "document")]
        public TextTranslatorDALDocument Document { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public TextTranslatorDALModel Model { get; set; }

    }
}
