// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALApplicationSubscriptions
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALApplicationSubscriptions class.
        /// </summary>
        public TextTranslatorDALApplicationSubscriptions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALApplicationSubscriptions class.
        /// </summary>
        public TextTranslatorDALApplicationSubscriptions(long? id = default(long?), string applicationIdentifier = default(string), string resourceId = default(string), string billingRegion = default(string), string encryptionScopeName = default(string), string dataRegion = default(string), bool? isCMKEnabled = default(bool?), TextTranslatorDALApplication applicationIdentifierNavigation = default(TextTranslatorDALApplication), TextTranslatorDALBillingRegions billingRegionNavigation = default(TextTranslatorDALBillingRegions), TextTranslatorDALBillingRegions dataRegionNavigation = default(TextTranslatorDALBillingRegions))
        {
            Id = id;
            ApplicationIdentifier = applicationIdentifier;
            ResourceId = resourceId;
            BillingRegion = billingRegion;
            EncryptionScopeName = encryptionScopeName;
            DataRegion = dataRegion;
            IsCMKEnabled = isCMKEnabled;
            ApplicationIdentifierNavigation = applicationIdentifierNavigation;
            BillingRegionNavigation = billingRegionNavigation;
            DataRegionNavigation = dataRegionNavigation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationIdentifier")]
        public string ApplicationIdentifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceId")]
        public string ResourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billingRegion")]
        public string BillingRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "encryptionScopeName")]
        public string EncryptionScopeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataRegion")]
        public string DataRegion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isCMKEnabled")]
        public bool? IsCMKEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationIdentifierNavigation")]
        public TextTranslatorDALApplication ApplicationIdentifierNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billingRegionNavigation")]
        public TextTranslatorDALBillingRegions BillingRegionNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataRegionNavigation")]
        public TextTranslatorDALBillingRegions DataRegionNavigation { get; set; }

    }
}
