// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALUploadHistory
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALUploadHistory
        /// class.
        /// </summary>
        public TextTranslatorDALUploadHistory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALUploadHistory
        /// class.
        /// </summary>
        /// <param name="status">Possible values include: 'default',
        /// 'userFilesUploaded', 'processing', 'extracting', 'extracted',
        /// 'validating', 'sentenceBreaking', 'processedFilesUploading',
        /// 'failed', 'succeeded'</param>
        public TextTranslatorDALUploadHistory(int? id = default(int?), System.Guid? jobId = default(System.Guid?), int? applicationId = default(int?), int? parentId = default(int?), string name = default(string), string extension = default(string), string blobContainerName = default(string), string blobLocation = default(string), string languageCode = default(string), string summary = default(string), bool? allowOverwrite = default(bool?), string status = default(string), System.Guid? createdBy = default(System.Guid?), System.DateTime? createdDate = default(System.DateTime?), System.DateTime? modifiedDate = default(System.DateTime?), int? documentTypeId = default(int?), string documentName = default(string), TextTranslatorDALApplication application = default(TextTranslatorDALApplication), TextTranslatorDALDocumentType documentType = default(TextTranslatorDALDocumentType), TextTranslatorDALApplicationUser createdByNavigation = default(TextTranslatorDALApplicationUser))
        {
            Id = id;
            JobId = jobId;
            ApplicationId = applicationId;
            ParentId = parentId;
            Name = name;
            Extension = extension;
            BlobContainerName = blobContainerName;
            BlobLocation = blobLocation;
            LanguageCode = languageCode;
            Summary = summary;
            AllowOverwrite = allowOverwrite;
            Status = status;
            CreatedBy = createdBy;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            DocumentTypeId = documentTypeId;
            DocumentName = documentName;
            Application = application;
            DocumentType = documentType;
            CreatedByNavigation = createdByNavigation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "jobId")]
        public System.Guid? JobId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public int? ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentId")]
        public int? ParentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "extension")]
        public string Extension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blobContainerName")]
        public string BlobContainerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blobLocation")]
        public string BlobLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languageCode")]
        public string LanguageCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "summary")]
        public string Summary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allowOverwrite")]
        public bool? AllowOverwrite { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'default',
        /// 'userFilesUploaded', 'processing', 'extracting', 'extracted',
        /// 'validating', 'sentenceBreaking', 'processedFilesUploading',
        /// 'failed', 'succeeded'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public System.Guid? CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentTypeId")]
        public int? DocumentTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentName")]
        public string DocumentName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "application")]
        public TextTranslatorDALApplication Application { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public TextTranslatorDALDocumentType DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdByNavigation")]
        public TextTranslatorDALApplicationUser CreatedByNavigation { get; set; }

    }
}
