// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALDocumentFiles
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALDocumentFiles
        /// class.
        /// </summary>
        public TextTranslatorDALDocumentFiles()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALDocumentFiles
        /// class.
        /// </summary>
        public TextTranslatorDALDocumentFiles(long? id = default(long?), long? documentId = default(long?), long? fileId = default(long?), TextTranslatorDALDocument document = default(TextTranslatorDALDocument), TextTranslatorDALFile file = default(TextTranslatorDALFile))
        {
            Id = id;
            DocumentId = documentId;
            FileId = fileId;
            Document = document;
            File = file;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentId")]
        public long? DocumentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileId")]
        public long? FileId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "document")]
        public TextTranslatorDALDocument Document { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "file")]
        public TextTranslatorDALFile File { get; set; }

    }
}
