// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A container for workspace results
    /// </summary>
    public partial class TextTranslatorModelsResponseTextTranslatorWorkspacesReponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorWorkspacesReponse class.
        /// </summary>
        public TextTranslatorModelsResponseTextTranslatorWorkspacesReponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorWorkspacesReponse class.
        /// </summary>
        /// <param name="workspaces">Gets or sets information for
        /// workspaces.</param>
        public TextTranslatorModelsResponseTextTranslatorWorkspacesReponse(IList<WorkspaceInfo> workspaces)
        {
            Workspaces = workspaces;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets information for workspaces.
        /// </summary>
        [JsonProperty(PropertyName = "workspaces")]
        public IList<WorkspaceInfo> Workspaces { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Workspaces == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Workspaces");
            }
            if (Workspaces != null)
            {
                foreach (var element in Workspaces)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
