// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Result container for test entries.
    /// </summary>
    public partial class TextTranslatorModelsResponseTextTranslatorTestEntriessResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorTestEntriessResponse
        /// class.
        /// </summary>
        public TextTranslatorModelsResponseTextTranslatorTestEntriessResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorTestEntriessResponse
        /// class.
        /// </summary>
        /// <param name="testEntries">Gets or sets Test result entries</param>
        public TextTranslatorModelsResponseTextTranslatorTestEntriessResponse(IList<TextTranslatorModelsTextTranslatorTestEntry> testEntries)
        {
            TestEntries = testEntries;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets Test result entries
        /// </summary>
        [JsonProperty(PropertyName = "testEntries")]
        public IList<TextTranslatorModelsTextTranslatorTestEntry> TestEntries { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (TestEntries == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TestEntries");
            }
            if (TestEntries != null)
            {
                foreach (var element in TestEntries)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
