// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A container for project results.
    /// </summary>
    public partial class TextTranslatorModelsResponseTextTranslatorProjectsResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorProjectsResponse class.
        /// </summary>
        public TextTranslatorModelsResponseTextTranslatorProjectsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorProjectsResponse class.
        /// </summary>
        /// <param name="projects">Gets or sets projects</param>
        /// <param name="pageIndex">Gets or sets the page index.</param>
        /// <param name="totalPageCount">Gets or sets the total number of
        /// pages.</param>
        public TextTranslatorModelsResponseTextTranslatorProjectsResponse(IList<TextTranslatorModelsTextTranslatorProjectInfo> projects, int pageIndex, int totalPageCount)
        {
            Projects = projects;
            PageIndex = pageIndex;
            TotalPageCount = totalPageCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets projects
        /// </summary>
        [JsonProperty(PropertyName = "projects")]
        public IList<TextTranslatorModelsTextTranslatorProjectInfo> Projects { get; set; }

        /// <summary>
        /// Gets or sets the page index.
        /// </summary>
        [JsonProperty(PropertyName = "pageIndex")]
        public int PageIndex { get; set; }

        /// <summary>
        /// Gets or sets the total number of pages.
        /// </summary>
        [JsonProperty(PropertyName = "totalPageCount")]
        public int TotalPageCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Projects == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Projects");
            }
            if (Projects != null)
            {
                foreach (var element in Projects)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
