// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TextTranslatorDALRegion
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALRegion class.
        /// </summary>
        public TextTranslatorDALRegion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALRegion class.
        /// </summary>
        public TextTranslatorDALRegion(int? id = default(int?), string regionName = default(string), IList<TextTranslatorDALProjectBilling> billing = default(IList<TextTranslatorDALProjectBilling>))
        {
            Id = id;
            RegionName = regionName;
            Billing = billing;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "regionName")]
        public string RegionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billing")]
        public IList<TextTranslatorDALProjectBilling> Billing { get; set; }

    }
}
