// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TextTranslatorModelsResponseTextTranslatorBaseDocumentResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorBaseDocumentResponse
        /// class.
        /// </summary>
        public TextTranslatorModelsResponseTextTranslatorBaseDocumentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorBaseDocumentResponse
        /// class.
        /// </summary>
        public TextTranslatorModelsResponseTextTranslatorBaseDocumentResponse(IList<TextTranslatorModelsTextTranslatorBaseDocumentInfo> documents = default(IList<TextTranslatorModelsTextTranslatorBaseDocumentInfo>))
        {
            Documents = documents;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documents")]
        public IList<TextTranslatorModelsTextTranslatorBaseDocumentInfo> Documents { get; set; }

    }
}
