// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Class for a single workspace permission request.
    /// </summary>
    public partial class TextTranslatorModelsRequestTextTranslatorWorkspacePermissionInfo
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsRequestTextTranslatorWorkspacePermissionInfo
        /// class.
        /// </summary>
        public TextTranslatorModelsRequestTextTranslatorWorkspacePermissionInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsRequestTextTranslatorWorkspacePermissionInfo
        /// class.
        /// </summary>
        /// <param name="emailAddress">Gets or sets the email address for the
        /// user this workspace has been
        /// shared with.</param>
        /// <param name="roleId">Gets or sets the id for this role.</param>
        public TextTranslatorModelsRequestTextTranslatorWorkspacePermissionInfo(string emailAddress, int roleId)
        {
            EmailAddress = emailAddress;
            RoleId = roleId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the email address for the user this workspace has been
        /// shared with.
        /// </summary>
        [JsonProperty(PropertyName = "emailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// Gets or sets the id for this role.
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public int RoleId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EmailAddress == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EmailAddress");
            }
        }
    }
}
