// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A class containing references to documents and corresponding processed
    /// documents.
    /// </summary>
    public partial class TextTranslatorModelsTextTranslatorDocumentInstance
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsTextTranslatorDocumentInstance class.
        /// </summary>
        public TextTranslatorModelsTextTranslatorDocumentInstance()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsTextTranslatorDocumentInstance class.
        /// </summary>
        /// <param name="documentInfo">Gets or sets the document</param>
        /// <param name="processedDocumentInfo">Gets or sets the processed
        /// document</param>
        public TextTranslatorModelsTextTranslatorDocumentInstance(TextTranslatorModelsTextTranslatorDocumentInfo documentInfo = default(TextTranslatorModelsTextTranslatorDocumentInfo), TextTranslatorModelsTextTranslatorProcessedDocumentInfo processedDocumentInfo = default(TextTranslatorModelsTextTranslatorProcessedDocumentInfo))
        {
            DocumentInfo = documentInfo;
            ProcessedDocumentInfo = processedDocumentInfo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the document
        /// </summary>
        [JsonProperty(PropertyName = "documentInfo")]
        public TextTranslatorModelsTextTranslatorDocumentInfo DocumentInfo { get; set; }

        /// <summary>
        /// Gets or sets the processed document
        /// </summary>
        [JsonProperty(PropertyName = "processedDocumentInfo")]
        public TextTranslatorModelsTextTranslatorProcessedDocumentInfo ProcessedDocumentInfo { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DocumentInfo != null)
            {
                DocumentInfo.Validate();
            }
            if (ProcessedDocumentInfo != null)
            {
                ProcessedDocumentInfo.Validate();
            }
        }
    }
}
