// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALApplicationSharing
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALApplicationSharing class.
        /// </summary>
        public TextTranslatorDALApplicationSharing()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALApplicationSharing class.
        /// </summary>
        public TextTranslatorDALApplicationSharing(long? id = default(long?), int? applicationId = default(int?), System.Guid? applicationUserId = default(System.Guid?), int? roleId = default(int?), bool? isDefaultApplication = default(bool?), TextTranslatorDALApplicationUser applicationUser = default(TextTranslatorDALApplicationUser), TextTranslatorDALApplication application = default(TextTranslatorDALApplication), TextTranslatorDALRole role = default(TextTranslatorDALRole))
        {
            Id = id;
            ApplicationId = applicationId;
            ApplicationUserId = applicationUserId;
            RoleId = roleId;
            IsDefaultApplication = isDefaultApplication;
            ApplicationUser = applicationUser;
            Application = application;
            Role = role;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public int? ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationUserId")]
        public System.Guid? ApplicationUserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleId")]
        public int? RoleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDefaultApplication")]
        public bool? IsDefaultApplication { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationUser")]
        public TextTranslatorDALApplicationUser ApplicationUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "application")]
        public TextTranslatorDALApplication Application { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "role")]
        public TextTranslatorDALRole Role { get; set; }

    }
}
