// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TextTranslatorDALProject
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALProject class.
        /// </summary>
        public TextTranslatorDALProject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALProject class.
        /// </summary>
        public TextTranslatorDALProject(System.Guid? id = default(System.Guid?), int? applicationId = default(int?), int? categoryId = default(int?), string categoryDescriptor = default(string), string projectName = default(string), string projectLabel = default(string), string description = default(string), byte[] status = default(byte[]), bool? isDeleted = default(bool?), System.Guid? createdBy = default(System.Guid?), System.Guid? modifiedBy = default(System.Guid?), System.DateTime? createdDate = default(System.DateTime?), System.DateTime? modifiedDate = default(System.DateTime?), int? languagePairId = default(int?), TextTranslatorDALApplication application = default(TextTranslatorDALApplication), TextTranslatorDALCategory category = default(TextTranslatorDALCategory), TextTranslatorDALApplicationUser createdByNavigation = default(TextTranslatorDALApplicationUser), TextTranslatorDALLanguagePair languagePair = default(TextTranslatorDALLanguagePair), TextTranslatorDALApplicationUser modifiedByNavigation = default(TextTranslatorDALApplicationUser), IList<TextTranslatorDALProjectCredit> projectCredit = default(IList<TextTranslatorDALProjectCredit>), IList<TextTranslatorDALModel> model = default(IList<TextTranslatorDALModel>), IList<TextTranslatorDALProjectBilling> billing = default(IList<TextTranslatorDALProjectBilling>), IList<TextTranslatorDALProjectBillingAudit> billingAudits = default(IList<TextTranslatorDALProjectBillingAudit>))
        {
            Id = id;
            ApplicationId = applicationId;
            CategoryId = categoryId;
            CategoryDescriptor = categoryDescriptor;
            ProjectName = projectName;
            ProjectLabel = projectLabel;
            Description = description;
            Status = status;
            IsDeleted = isDeleted;
            CreatedBy = createdBy;
            ModifiedBy = modifiedBy;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            LanguagePairId = languagePairId;
            Application = application;
            Category = category;
            CreatedByNavigation = createdByNavigation;
            LanguagePair = languagePair;
            ModifiedByNavigation = modifiedByNavigation;
            ProjectCredit = projectCredit;
            Model = model;
            Billing = billing;
            BillingAudits = billingAudits;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationId")]
        public int? ApplicationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public int? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categoryDescriptor")]
        public string CategoryDescriptor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectName")]
        public string ProjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectLabel")]
        public string ProjectLabel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public byte[] Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdBy")]
        public System.Guid? CreatedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedBy")]
        public System.Guid? ModifiedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languagePairId")]
        public int? LanguagePairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "application")]
        public TextTranslatorDALApplication Application { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public TextTranslatorDALCategory Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdByNavigation")]
        public TextTranslatorDALApplicationUser CreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languagePair")]
        public TextTranslatorDALLanguagePair LanguagePair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedByNavigation")]
        public TextTranslatorDALApplicationUser ModifiedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectCredit")]
        public IList<TextTranslatorDALProjectCredit> ProjectCredit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public IList<TextTranslatorDALModel> Model { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billing")]
        public IList<TextTranslatorDALProjectBilling> Billing { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "billingAudits")]
        public IList<TextTranslatorDALProjectBillingAudit> BillingAudits { get; set; }

    }
}
