// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TextTranslatorDALProcessedDocument
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALProcessedDocument class.
        /// </summary>
        public TextTranslatorDALProcessedDocument()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorDALProcessedDocument class.
        /// </summary>
        public TextTranslatorDALProcessedDocument(long? id = default(long?), long? modelId = default(long?), byte[] documentType = default(byte[]), long? alignedSentenceCount = default(long?), long? usedSentenceCount = default(long?), long? documentId = default(long?), TextTranslatorDALDocument document = default(TextTranslatorDALDocument), TextTranslatorDALModel model = default(TextTranslatorDALModel))
        {
            Id = id;
            ModelId = modelId;
            DocumentType = documentType;
            AlignedSentenceCount = alignedSentenceCount;
            UsedSentenceCount = usedSentenceCount;
            DocumentId = documentId;
            Document = document;
            Model = model;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modelId")]
        public long? ModelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentType")]
        public byte[] DocumentType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alignedSentenceCount")]
        public long? AlignedSentenceCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usedSentenceCount")]
        public long? UsedSentenceCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentId")]
        public long? DocumentId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "document")]
        public TextTranslatorDALDocument Document { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public TextTranslatorDALModel Model { get; set; }

    }
}
