// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CustomTranslator.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TextTranslatorDALApplicationUser
    {
        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALApplicationUser
        /// class.
        /// </summary>
        public TextTranslatorDALApplicationUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TextTranslatorDALApplicationUser
        /// class.
        /// </summary>
        public TextTranslatorDALApplicationUser(System.Guid? id = default(System.Guid?), string userName = default(string), string organizationName = default(string), string inviteEmail = default(string), System.DateTime? createdDate = default(System.DateTime?), System.DateTime? modifiedDate = default(System.DateTime?), bool? isNewUser = default(bool?), IList<TextTranslatorDALDocument> documentCreatedByNavigation = default(IList<TextTranslatorDALDocument>), IList<TextTranslatorDALDocument> documentModifiedByNavigation = default(IList<TextTranslatorDALDocument>), IList<TextTranslatorDALFile> file = default(IList<TextTranslatorDALFile>), IList<TextTranslatorDALModel> modelCreatedByNavigation = default(IList<TextTranslatorDALModel>), IList<TextTranslatorDALModel> modelModifiedByNavigation = default(IList<TextTranslatorDALModel>), IList<TextTranslatorDALProject> projectCreatedByNavigation = default(IList<TextTranslatorDALProject>), IList<TextTranslatorDALProject> projectModifiedByNavigation = default(IList<TextTranslatorDALProject>), IList<TextTranslatorDALTest> testCreatedByNavigation = default(IList<TextTranslatorDALTest>), IList<TextTranslatorDALTest> testModifiedByNavigation = default(IList<TextTranslatorDALTest>), IList<TextTranslatorDALUploadHistory> uploadHistoryCreatedByNavigation = default(IList<TextTranslatorDALUploadHistory>), IList<TextTranslatorDALApplication> applications = default(IList<TextTranslatorDALApplication>), IList<TextTranslatorDALApplicationSharing> applicationSharings = default(IList<TextTranslatorDALApplicationSharing>))
        {
            Id = id;
            UserName = userName;
            OrganizationName = organizationName;
            InviteEmail = inviteEmail;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            IsNewUser = isNewUser;
            DocumentCreatedByNavigation = documentCreatedByNavigation;
            DocumentModifiedByNavigation = documentModifiedByNavigation;
            File = file;
            ModelCreatedByNavigation = modelCreatedByNavigation;
            ModelModifiedByNavigation = modelModifiedByNavigation;
            ProjectCreatedByNavigation = projectCreatedByNavigation;
            ProjectModifiedByNavigation = projectModifiedByNavigation;
            TestCreatedByNavigation = testCreatedByNavigation;
            TestModifiedByNavigation = testModifiedByNavigation;
            UploadHistoryCreatedByNavigation = uploadHistoryCreatedByNavigation;
            Applications = applications;
            ApplicationSharings = applicationSharings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "organizationName")]
        public string OrganizationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inviteEmail")]
        public string InviteEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isNewUser")]
        public bool? IsNewUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentCreatedByNavigation")]
        public IList<TextTranslatorDALDocument> DocumentCreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "documentModifiedByNavigation")]
        public IList<TextTranslatorDALDocument> DocumentModifiedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "file")]
        public IList<TextTranslatorDALFile> File { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modelCreatedByNavigation")]
        public IList<TextTranslatorDALModel> ModelCreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modelModifiedByNavigation")]
        public IList<TextTranslatorDALModel> ModelModifiedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectCreatedByNavigation")]
        public IList<TextTranslatorDALProject> ProjectCreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "projectModifiedByNavigation")]
        public IList<TextTranslatorDALProject> ProjectModifiedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "testCreatedByNavigation")]
        public IList<TextTranslatorDALTest> TestCreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "testModifiedByNavigation")]
        public IList<TextTranslatorDALTest> TestModifiedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uploadHistoryCreatedByNavigation")]
        public IList<TextTranslatorDALUploadHistory> UploadHistoryCreatedByNavigation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applications")]
        public IList<TextTranslatorDALApplication> Applications { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "applicationSharings")]
        public IList<TextTranslatorDALApplicationSharing> ApplicationSharings { get; set; }

    }
}
