// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Result container for file content.
    /// </summary>
    public partial class TextTranslatorModelsResponseTextTranslatorFileContentResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorFileContentResponse
        /// class.
        /// </summary>
        public TextTranslatorModelsResponseTextTranslatorFileContentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TextTranslatorModelsResponseTextTranslatorFileContentResponse
        /// class.
        /// </summary>
        /// <param name="items">Gets or sets the items of the document</param>
        /// <param name="totalExtractedSentences">Gets or sets the total number
        /// of extracted sentences.</param>
        /// <param name="pageIndex">Gets or sets the page index.</param>
        /// <param name="totalPageCount">Gets or sets the total number of
        /// pages.</param>
        public TextTranslatorModelsResponseTextTranslatorFileContentResponse(IList<string> items, long totalExtractedSentences, int pageIndex, int totalPageCount)
        {
            Items = items;
            TotalExtractedSentences = totalExtractedSentences;
            PageIndex = pageIndex;
            TotalPageCount = totalPageCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the items of the document
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<string> Items { get; set; }

        /// <summary>
        /// Gets or sets the total number of extracted sentences.
        /// </summary>
        [JsonProperty(PropertyName = "totalExtractedSentences")]
        public long TotalExtractedSentences { get; set; }

        /// <summary>
        /// Gets or sets the page index.
        /// </summary>
        [JsonProperty(PropertyName = "pageIndex")]
        public int PageIndex { get; set; }

        /// <summary>
        /// Gets or sets the total number of pages.
        /// </summary>
        [JsonProperty(PropertyName = "totalPageCount")]
        public int TotalPageCount { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Items == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Items");
            }
        }
    }
}
